name: Release

on:
  push:
    branches:
    - main

jobs:
  run:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image to GitHub Container Registry
      run: |
        docker build . --tag hello-container --build-arg "VERSION_NOTE=at ${GITHUB_SHA}"

        for tag in ${{ github.run_number }} latest; do
          docker tag hello-container ghcr.io/upcloudltd/hello:$tag
          docker push ghcr.io/upcloudltd/hello:$tag
        done
