name: Test

on:
  pull_request:
    branches:
    - main

jobs:
  build-and-push:
    name: Validate txt response
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build container and check response
      run: |
        docker build . --tag hello-container --build-arg "VERSION_NOTE=at not-a-commit-sha"
        container_id=$(docker run -d -p 8080:80 --hostname hello-test hello-container)

        curl localhost:8080 -so out.txt

        grep -q "^Hostname: hello-test$" out.txt
        grep -q "^Hello! 👋$" out.txt
        grep -q "^UpCloudLtd / hello-container at not-a-co$" out.txt

        docker rm -f ${container_id}
